name: 自动部署
on:
  push:
    branches: [main] # 监听 main 分支的 push 事件

permissions:
  contents: write # 允许写入仓库内容

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with: { node-version: 22 }

      - name: 安装依赖
        run: npm install

      - name: 运行测试
        run: npm run test

      - name: 打包代码
        run: npm run build

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./dist
